In [ ]:
%matplotlib inline


# 텐서(Tensor)

텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조입니다.
PyTorch에서는 텐서를 사용하여 모델의 입력과 출력뿐만 아니라 모델의 매개변수를 부호화(encode)합니다.

GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행할 수 있다는 점을 제외하면, 텐서는 NumPy의 ndarray와 매우 유사합니다.


In [2]:
import torch
import numpy as np

# 1D with tensor and np


In [19]:
np_array = np.array([0., 1., 2., 3.])
t = torch.FloatTensor([0, 1, 2, 3])
print(np_array)
print(t)

[0. 1. 2. 3. 4.]
tensor([0., 1., 2., 3.])


In [20]:
print('Rank of t: ', np_array.ndim)
print('Shape of t: ', np_array.shape)

Rank of t:  1
Shape of t:  (5,)


In [21]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([4])
torch.Size([4])


# 2D with tensor and np



In [22]:
np_array = np.array([[1., 2., 3.],
                     [4., 5., 6.],
                     [7., 8., 9.],
                     [10., 11., 12.]])
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]
                      ])
print(np_array)
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [23]:
print('Rank of t: ', np_array.ndim)
print('Shape of t: ', np_array.shape)

Rank of t:  2
Shape of t:  (4, 3)


In [24]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


# Matrix Multiplication Vs. Multiplication

In [25]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [26]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# Sum

In [31]:
t = torch.FloatTensor([[1, 2], [3, 4], [5,6]])
print(t)
print(t.size())

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


In [34]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0))
print(t.sum(dim=1)) 
print(t.sum(dim=-1))

tensor(21.)
tensor([ 9., 12.])
tensor([ 3.,  7., 11.])
tensor([ 3.,  7., 11.])


--------------




#max and argmax

In [45]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [46]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [47]:
print(torch.argmax(t,dim=0))

tensor([1, 1])


--------------




## view



In [49]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [50]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [52]:
print(ft.view([-1, 3, 3]))
print(ft.view([-1, 3, 3]).shape)


RuntimeError: ignored

#squeeze and unsqueeze

In [53]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [54]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [55]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [56]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [17]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영됩니다.



In [18]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy 배열을 텐서로 변환하기



In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 텐서에 반영됩니다.



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")